### PR TITLE
Upgrade openrave for ubuntu 18.04:

### PR DESCRIPTION
**Pull request by nicholasadr**
- Compiles with pybind instead of downgrading boost
- Add git credentials check, set to a placeholder if none
- Add pyopengl installation
- OpenRAVE v0.53.1

### CODE REVIEW

**Comment by cielavenir** [comment]
as a provisioning script, you should use `git config --local`, not --global.

[edit] to avoid surprise: I'm from Mujin.

**Comment by nicholasadr** [comment]
This is really late but thanks @cielavenir for pointing that out

**Comment by cielavenir** [comment]
lol, didn't know ipsum.com is registered by Google :joy:

**Comment by nicholasadr** [comment]
thanks @cielavenir for pointing that out

**Pull request merged**
